["BWA3_Leopard2_Fleck","BWA3_Leopard2_Tropen","BWA3_Leopard2_Fleck","BWA3_Leopard2_Tropen","BWA3_Leopard2_Fleck","O_MBT_04_cannon_F","I_MBT_03_cannon_F","I_MBT_03_cannon_F","rhsgref_cdf_b_t80uk_tv","rhsgref_cdf_b_t80u_tv","I_MBT_03_cannon_F","I_MBT_03_cannon_F","I_MBT_03_cannon_F","BWA3_Leopard2_Fleck","rhsgref_cdf_b_t80u_tv","rhsgref_cdf_b_t80u_tv","rhsusf_m1a1fep_wd","rhsusf_m1a1fep_od","rhsusf_m1a1hc_wd"],  //主战坦克
["O_APC_Tracked_02_cannon_F","I_APC_tracked_03_cannon_F","BWA3_Puma_Fleck","BWA3_Puma_Tropen","BWA3_Puma_Fleck","BWA3_Puma_Tropen"], //步兵战车以及APC
["rhsgref_cdf_b_btr80","O_APC_Wheeled_02_rcws_v2_F","I_APC_Wheeled_03_cannon_F","rhsgref_ins_btr70","rhsgref_ins_g_btr70"], //APC
["rhsgref_ins_zsu234","rhsgref_ins_zsu234","rhsgref_ins_zsu234","rhsgref_ins_zsu234","O_APC_Tracked_02_AA_F","O_APC_Tracked_02_AA_F"], //战区机动防空
["I_MRAP_03_hmg_F","I_MRAP_03_gmg_F","rhsgref_ins_g_bmp1p","I_LT_01_AT_F","BWA3_Dingo2_FLW100_MG3_Fleck","I_LT_01_scout_F","I_LT_01_cannon_F","rhsgref_cdf_b_gaz66_zu23","BWA3_Dingo2_FLW200_GMW_Fleck","BWA3_Dingo2_FLW200_M2_Fleck","BWA3_Dingo2_FLW200_GMW_CG13_Fleck","BWA3_Dingo2_FLW200_M2_CG13_Fleck","BWA3_Dingo2_FLW100_MG3_CG13_Fleck","BWA3_Eagle_FLW100_Fleck","rhsgref_ins_btr70"], //巡逻、输送的大型防雷车，装甲输送车,执行重要作战任务的装甲单位
["rhsgref_cdf_b_2s1_at","rhsgref_cdf_b_2s1_at","rhsgref_cdf_b_2s1_at","rhsgref_cdf_b_t80bv_tv","rhsgref_ins_g_t72ba","BWA3_Panzerhaubitze2000_Fleck","BWA3_Panzerhaubitze2000_Fleck","BWA3_Panzerhaubitze2000_Fleck","BWA3_Panzerhaubitze2000_Fleck","BWA3_Panzerhaubitze2000_Fleck","O_MBT_02_arty_F","O_MBT_02_arty_F","BWA3_Panzerhaubitze2000_Fleck","BWA3_Panzerhaubitze2000_Fleck","I_Truck_02_MRL_F","I_Truck_02_MRL_F","BWA3_Multi_Fleck","BWA3_Multi_Fleck","BWA3_Multi_Fleck"], //自行火炮 突击炮 坦克歼击车 火力支援车辆 后勤车辆
["B_SAM_System_01_F","B_SAM_System_01_F","B_SAM_System_02_F","B_SAM_System_02_F","B_SAM_System_02_F"],  //GL  现在是防空 ,"B_Radar_System_01_F" ,"B_SAM_System_02_F"
["I_HMG_02_high_F","I_HMG_02_high_F","I_GMG_01_high_F","I_HMG_02_high_F","rhsgref_cdf_b_DSHKM","rhsgref_cdf_b_ZU23","rhssaf_army_metis_9k115","rhssaf_army_metis_9k115","I_static_AT_F","rhsgref_cdf_b_DSHKM","rhsgref_ins_g_Igla_AA_pod"],    //MG  现在是地面防御(当前为防空/反装甲)            "rhsgref_ins_g_DSHKM","rhsgref_ins_g_SPG9M","rhssaf_army_m2staticmg_minitripod","rhssaf_army_nsv_tripod","rhssaf_army_ags30_tripod","I_HMG_02_F","I_HMG_02_high_F"
["BWA3_MRS120_Fleck","BWA3_MRS120_Fleck","rhsgref_ins_g_d30_at","rhs_prv13_turret_vpvo","O_SAM_System_04_F","I_static_AT_F","rhsgref_ins_g_SPG9M","B_SAM_System_02_F"],//重点防御阵地
["rhsgref_ins_kraz255b1_fuel"],
["I_Truck_02_box_F"],
["I_Truck_02_ammo_F"],
["O_UAV_01_F","O_UAV_06_F","I_UGV_01_rcws_F","I_UGV_01_rcws_F"]
