["rhsgref_ins_g_t72bc","rhsgref_ins_g_t72bb","rhsgref_ins_g_t72ba","O_MBT_04_cannon_F","I_MBT_03_cannon_F","rhsgref_cdf_b_t80bv_tv","rhsgref_cdf_b_t80b_tv","rhsgref_cdf_b_t80uk_tv","rhsgref_cdf_b_t80u_tv","O_MBT_04_command_F","O_MBT_02_cannon_F","rhsusf_m1a1fep_od","rhsusf_m1a1fep_wd","rhsusf_m1a1hc_wd"],  //主战坦克
["O_APC_Tracked_02_cannon_F","I_APC_tracked_03_cannon_F","I_APC_Wheeled_03_cannon_F","rhsgref_cdf_b_bmd1p","rhsgref_cdf_b_bmd2k","rhsgref_ins_g_bmp1p","rhsgref_cdf_bmp2","rhsgref_cdf_bmp2d"], //步兵战车以及APC
["rhsgref_cdf_b_btr80","O_APC_Wheeled_02_rcws_v2_F","rhsgref_cdf_b_btr60","rhsgref_ins_btr70","rhsgref_ins_g_btr70"], //APC
["rhsgref_ins_zsu234","rhsgref_ins_zsu234","RDS_ZSU_ChDKZ","RDS_ZSU_TK","O_APC_Tracked_02_AA_F","O_APC_Tracked_02_AA_F"], //战区机动防空
["I_MRAP_03_hmg_F","I_MRAP_03_gmg_F","I_LT_01_AA_F","I_LT_01_scout_F","I_LT_01_cannon_F","I_LT_01_AT_F","rhsgref_cdf_b_reg_uaz_dshkm","rhsgref_cdf_b_reg_uaz_ags","rhsgref_cdf_b_reg_uaz","I_C_Offroad_02_AT_F","I_C_Offroad_02_LMG_F","rhsgref_cdf_b_gaz66_ap2","rhsgref_ins_g_2s1_at","rhsgref_cdf_b_gaz66_zu23","rhsgref_BRDM2_ins_g","rhsgref_BRDM2_ATGM_ins_g","RDS_BMP2_Ambul_TK","RDS_T55A_AAF","RDS_T34_AAF","RDS_T55A_AAF","RDS_BMP2_HQ_TK"], //巡逻、输送的大型防雷车，装甲输送车,执行重要作战任务的装甲单位
["rhssaf_m1151_olive_pkm","rhssaf_m1025_olive_m2","O_MBT_02_arty_F","O_MBT_02_arty_F","O_MBT_02_arty_F","O_MBT_02_arty_F","O_MBT_02_arty_F","O_MBT_02_arty_F","O_MBT_02_arty_F","rhsgref_ins_BM21","rhsgref_ins_BM21","I_Truck_02_MRL_F","I_Truck_02_MRL_F","rhsgref_ins_gaz66_ammo","rhsgref_ins_kraz255b1_fuel","rhsgref_ins_ural_repair"], //轻装甲掩护下的自行火炮师车辆 "rhsgref_BRDM2_ins_g","rhsgref_BRDM2_ATGM_ins_g","rhssaf_army_ural_fuel","rhssaf_m1151_olive_pkm","rhssaf_m1025_olive_m2","rhsgref_cdf_gaz66_ammo","rhsgref_cdf_b_reg_uaz_spg9","rhsgref_cdf_b_reg_uaz_dshkm","rhsgref_cdf_b_reg_uaz_ags","rhsgref_cdf_b_reg_uaz","I_C_Offroad_02_AT_F","I_C_Offroad_02_LMG_F","rhsgref_ins_BM21","rhsgref_ins_BM21","rhsgref_ins_BM21","rhsgref_ins_BM21","RDS_BMP2_Ambul_TK","RDS_BMP2_Ambul_ChDKZ","iaf_gypsy_LMG"
["B_SAM_System_01_F","B_SAM_System_01_F","rhs_prv13_turret_vpvo"],  //GL  现在是防空 ,"B_Radar_System_01_F"
["I_HMG_02_F","I_HMG_02_high_F","rhsgref_ins_g_Igla_AA_pod","rhsgref_ins_g_DSHKM","rhsgref_ins_g_SPG9M","rhssaf_army_m2staticmg_minitripod","rhssaf_army_nsv_tripod","rhssaf_army_ags30_tripod","rhssaf_army_metis_9k115","pook_M777","rhsgref_cdf_b_ZU23"],    //MG  现在是地面防御
["rhsgref_ins_g_2b14","rhsgref_ins_g_d30","pook_M777","rhsgref_ins_g_d30_at","O_SAM_System_04_F","O_SAM_System_04_F"],//重点防御阵地
["rhsgref_ins_kraz255b1_fuel"],
["I_Truck_02_box_F"],
["I_Truck_02_ammo_F"],
["O_UAV_01_F","O_UAV_06_F","O_UGV_01_rcws_F"]